AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  AngelCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: angel.co web crawler
      FunctionName: angel-crawler
      CodeUri: ./angel-crawler
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256