AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce

Resources:

  CrunchbaseCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: crunchbase.com web crawler
      FunctionName: crunchbase-crawler
      CodeUri: ./crunchbase-crawler
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256
      Layers:
        - Ref: LayerDependencies
        
  AngelCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: angel.co web crawler
      FunctionName: angel-crawler
      CodeUri: ./angel-crawler
      Handler: app.lambda_handler
      Runtime: nodejs12.x
      MemorySize: 1024
      Layers:
        - Ref: LayerDependencies
      
  LayerDependencies:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: python-nodejs
      ContentUri: ./layers/dependencies/
      CompatibleRuntimes:
        - python3.8
        - nodejs12.x
      RetentionPolicy: Delete
      
  UpsellXServerlessAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'dev'
      EndpointConfiguration: REGIONAL
      OpenApiVersion: 3.0.3
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: upsellx-openapi.yaml