AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  AngelCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: angel.co web crawler
      FunctionName: angel-crawler
      CodeUri: ./angel-crawler
      Handler: app.lambda_handler
      Runtime: nodejs12.x
      MemorySize: 1600
      Layers:
        - Ref: LayerDependencies
      
  LayerDependencies:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: python
      ContentUri: ./layers/dependencies/
      CompatibleRuntimes:
        - python3.8
        - nodejs12.x
      RetentionPolicy: Delete